### ISSUE TITLE
Allied Vision USB3: Synchronous grab CPP getting error

### ISSUE THREAD

**Issue by Garrydcruz** [astuff/avt_vimba_camera#107]
z0172311@frdc36443:~/Documents/catkin_ws_av$ rosrun abc_qa abc_qa_node 
/home/z0172311/Documents/catkin_ws_av/devel/lib/abc_qa/abc_qa_node: symbol lookup error: /home/z0172311/Documents/catkin_ws_av/devel/lib/abc_qa/abc_qa_node: undefined symbol: _ZN3AVT6VmbAPI6Camera18AcquireSingleImageERNS0_10shared_ptrINS0_5FrameEEEjNS0_19FrameAllocationModeE
![Screenshot from 2022-10-03 16-54-03](https://user-images.githubusercontent.com/36693471/193569198-d155cc7f-fb7e-487f-97e6-cca5ae4e1fca.png)

**Comment by icolwell-as** [comment]
Please provide more information. There is no `abc_qa` package or `abc_qa_node` node defined in this repo.
