### ISSUE TITLE
Gain cannot be set

### ISSUE THREAD

**Issue by michaelschleiss** [astuff/avt_vimba_camera#24]
I cannot set the gain in dynamic reconfigure. I am getting the following warnings when the camera node is launched.

[ WARN] [1601656937.760431651]: [/cam_vo]: Could not get feature Gain
 Error: Not found.
[ WARN] [1601656937.764869844]: [/cam_vo]: Could not get feature DecimationHorizontal
 Error: Not found.
[ WARN] [1601656937.764939937]: [/cam_vo]: Could not get feature DecimationVertical
 Error: Not found.
[ WARN] [1601656937.770969267]: [/cam_vo]: Could not get feature PtpMode
 Error: Not found.
[ WARN] [1601656937.777396508]: [/cam_vo]: Could not get feature IrisAutoTarget
 Error: Not found.
[ WARN] [1601656937.777619918]: [/cam_vo]: Could not get feature IrisMode
 Error: Not found.
[ WARN] [1601656937.777709050]: [/cam_vo]: Could not get feature IrisVideoLevelMax
 Error: Not found.
[ WARN] [1601656937.777808284]: [/cam_vo]: Could not get feature IrisVideoLevelMin

Any idea about what this could be related.

**Comment by icolwell-as** [comment]
What version of ROS do you have and what launch file are you using to start the driver?

**Comment by icolwell-as** [comment]
Closing from lack of response.
