### ISSUE TITLE
USB camera, error "Could not start Vimba system: TL not loaded."

### ISSUE THREAD

**Issue by mac137** [astuff/avt_vimba_camera#29]
Hello! I plugged my USB Alvium 1800 U-319c camera and installed this ROS driver on my ubuntu 20.04 with ROS Noetic according to the instruction `sudo apt install ros-$ROS_DISTRO-avt-vimba-camera`.

When I do `roslaunch avt_vimba_camera mono_camera.launch` on a sourced terminal, it says: `[ERROR] [1614724799.379538586]: [Vimba System]: Could not start Vimba system: TL not loaded.`

Then, I downloaded `Vimba 4.2` from https://www.alliedvision.com/en/products/software.html, installed it, and set up the proper path to `GENICAM_GENTL64_PATH` so that when I do `echo $GENICAM_GENTL64_PATH` it gives me the correct path. However, when I try `roslaunch avt_vimba_camera mono_camera.launch`, it gives me the same error. 

I can add that when I open the VimbaViewer from `/vimba/Vimba_4_2/Tools/Viewer/Bin/x86_64bit`, everything works - I can see the listed camera and the video. But when I `make` for example `/vimba/Vimba_4_2/VimbaCPP/Examples/ListCameras/Build/Make` and then run `./vimba/Vimba_4_2/VimbaCPP/Examples/ListCameras/Build/Make/binary/x86_64bit/ListCameras` I get almost the same error `Could not start system. Error code: -16(TL not loaded.)`

Please help! How can successfully `roslaunch` your driver on ROS?

**Comment by PhilippSchmaelzle** [comment]
Hi, I'm using a GigE camera. But I received the same error whenever I forgot to execute the installation of `lib/VimbaX_X/VimbaGigETL/Install.sh`
There seems to be the same Installation possibility for USB cameras.  `sudo ... lib/VimbaX_X/VimbaUSBTL/Install.sh`

Was the solution for me

**Comment by mac137** [comment]
> Hi, I'm using a GigE camera. But I received the same error whenever I forgot to execute the installation of `lib/VimbaX_X/VimbaGigETL/Install.sh`
> There seems to be the same Installation possibility for USB cameras. `sudo ... lib/VimbaX_X/VimbaUSBTL/Install.sh`
> 
> Was the solution for me

Thx @PhilippSchmaelzle for your suggestion, but in my case, I do install `Vimba_4_2/VimbaUSBTL/Install.sh` and make sure that the `GENICAM_GENTL64_PATH` is properly set. Nevertheless, the error persists.

**Comment by mac137** [comment]
I reported this issue to Allied VIsion, and indeed, they agreed (after 2-hour remote testing on my PC) that this is a Vimba-related bug. I am waiting for their fix then.

**Comment by mac137** [comment]
Allied Vision said they have never bumped into this bug and they are working on it. In the meantime however, I have changed my PC and now `Vimba_4_2/VimbaCPP/Examples/ListCameras/Build/Make/binary/x86_64bit/ListCameras` works. However, this ROS driver still does not work with my USB camera as it keeps displaying this error `[Vimba System]: Could not start Vimba system: TL not loaded.`.

Does this ROS driver account for the 64bit version of vimba 4.2? I am asking because vimba 4.2 sets path to `GENICAM_GENTL64_PATH ` only. `GENICAM_GENTL32_PATH ` is empty. Even when I try to set the same path for `GENICAM_GENTL32_PATH ` as it is for `GENICAM_GENTL64_PATH `, this ROS driver still does not work.

Any ideas on how to fix that?

**Comment by Mickeyyyang** [comment]
> Allied Vision said they have never bumped into this bug and they are working on it. In the meantime however, I have changed my PC and now `Vimba_4_2/VimbaCPP/Examples/ListCameras/Build/Make/binary/x86_64bit/ListCameras` works. However, this ROS driver still does not work with my USB camera as it keeps displaying this error `[Vimba System]: Could not start Vimba system: TL not loaded.`.
> 
> Does this ROS driver account for the 64bit version of vimba 4.2? I am asking because vimba 4.2 sets path to `GENICAM_GENTL64_PATH ` only. `GENICAM_GENTL32_PATH ` is empty. Even when I try to set the same path for `GENICAM_GENTL32_PATH ` as it is for `GENICAM_GENTL64_PATH `, this ROS driver still does not work.
> 
> Any ideas on how to fix that?

Hi, Excuse me, have you solved this problem, I also encountered this problem...

**Comment by mac137** [comment]
> Hi, Excuse me, have you solved this problem, I also encountered this problem...

Hello. I bypassed this problem by writing simple drivers in python based on `Vimba_4_2/VimbaPython/examples/`

**Comment by Mickeyyyang** [comment]
Hi, Maciej~
     OK.
     Yes, I think you are right. I also made changes based on the official
Vimaba SDK, but it has not been successful. Can you share the driver file
that you have changed? Thx~
     Best wishes~

Maciej ***@***.***> 于2021年4月28日周三 上午6:37写道：

**Comment by mac137** [comment]
> Hi, Maciej~ OK. Yes, I think you are right. I also made changes based on the official Vimaba SDK, but it has not been successful. Can you share the driver file that you have changed? Thx~ Best wishes

You can find my USB driver here: [https://github.com/maciej-3/pp_alvium_driver](https://github.com/maciej-3/pp_alvium_driver)

**Comment by yulan0215** [comment]
> Hello! I plugged my USB Alvium 1800 U-319c camera and installed this ROS driver on my ubuntu 20.04 with ROS Noetic according to the instruction `sudo apt install ros-$ROS_DISTRO-avt-vimba-camera`.
> 
> When I do `roslaunch avt_vimba_camera mono_camera.launch` on a sourced terminal, it says: `[ERROR] [1614724799.379538586]: [Vimba System]: Could not start Vimba system: TL not loaded.`
> 
> Then, I downloaded `Vimba 4.2` from https://www.alliedvision.com/en/products/software.html, installed it, and set up the proper path to `GENICAM_GENTL64_PATH` so that when I do `echo $GENICAM_GENTL64_PATH` it gives me the correct path. However, when I try `roslaunch avt_vimba_camera mono_camera.launch`, it gives me the same error.
> 
> I can add that when I open the VimbaViewer from `/vimba/Vimba_4_2/Tools/Viewer/Bin/x86_64bit`, everything works - I can see the listed camera and the video. But when I `make` for example `/vimba/Vimba_4_2/VimbaCPP/Examples/ListCameras/Build/Make` and then run `./vimba/Vimba_4_2/VimbaCPP/Examples/ListCameras/Build/Make/binary/x86_64bit/ListCameras` I get almost the same error `Could not start system. Error code: -16(TL not loaded.)`
> 
> Please help! How can successfully `roslaunch` your driver on ROS?

Hi:

I used Alvium 1800U-1236C camera , which is the usb camera, do you think is it possible for me to directly use this driver to run my usb camera？ I knew the GUID of my camera...
Thx!

**Comment by icolwell-as** [comment]
@maciej-3 and @Mickeyyyang if there is anything you have discovered that may help this driver work better on USB cameras, I'd be happy to accept a PR or create the PR myself. Hoping to do a new ROS1 release soon, so would be good to get the fixes into the new release.

Thanks!

**Comment by icolwell-as** [comment]
For those who may come across this in the future, USB support has been added by this PR:
https://github.com/astuff/avt_vimba_camera/pull/54
