### ISSUE TITLE
Possibility of this ROS driver for USB3 camera

### ISSUE THREAD

**Issue by yulan0215** [astuff/avt_vimba_camera#32]
Hi:

I used AV Alvium 1800U camera but the problem is that I do not have IP for my AVT-camera. Do you know how to use this driver for my usb camera? Is it enough if I just use the GUID?
Thx!

**Comment by icolwell-as** [comment]
Hi @yulan0215, we haven't tried using this driver with anything other than ethernet cameras. 
That being said, I don't see anything in the code that prevents the use of USB cameras. I believe it should work by specifying the GUID.
