### ISSUE TITLE
`/camera/image_raw` header contains no useful information

### ISSUE THREAD

**Issue by GarethZhang** [astuff/avt_vimba_camera#69]
Hi,

Thank you for the amazing driver support!

When I ran `roslaunch avt_vimba_camera Mako_G-319.launch ip:=192.168.0.XXX`, the generated `/camera/image_raw` contains no useful header.

Reproduce:
```
roslaunch avt_vimba_camera Mako_G-319.launch ip:=192.168.0.XXX
rostopic echo /camera/image_raw/header
```

A sample output is the following:
```
seq: 31
stamp:
  secs: 0
  nsecs:         0
frame_id: ''
```

Thank you!

**Comment by icolwell-as** [comment]
Thanks for reporting this, I am able to reproduce the same issue.

**Comment by icolwell-as** [comment]
Found the issue, will post a fix shortly.
